apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: seeking-crawler-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: seeking-crawler
  minReplicas: 1
  maxReplicas: 128
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
