apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeking-api
  labels:
    app: seeking
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: seeking
  template:
    metadata:
      labels:
        app: seeking
    spec:
      containers:
      - name: seeking-api
        image: asia.gcr.io/YOUR_GCLOUD_ID/self-seeking
        ports:
        - containerPort: 8000
        env:
        - name: PROCESSES
          value: api
        - name: PORT
          value: "8000"
