apiVersion: apps/v1
kind: Deployment
metadata:
  name: identify-api
  labels:
    app: identify
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: identify
  template:
    metadata:
      labels:
        app: identify
    spec:
      containers:
      - name: identify-api
        image: asia.gcr.io/YOUR_GCLOUD_ID/identify
        ports:
        - containerPort: 8000
        env:
        - name: PROCESSES
          value: api
        - name: PORT
          value: "8000"
