apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeking-crawler
  labels:
    app: seeking
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: seeking
  template:
    metadata:
      labels:
        app: seeking
    spec:
      containers:
      - name: seeking-crawler
        image: asia.gcr.io/YOUR_GCLOUD_ID/self-seeking
        env:
        - name: PROCESSES
          value: crawler
