apiVersion: apps/v1
kind: Deployment
metadata:
  name: identify-crawler
  labels:
    app: identify
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: identify
  template:
    metadata:
      labels:
        app: identify
    spec:
      containers:
      - name: identify-crawler
        image: asia.gcr.io/YOUR_GCLOUD_ID/identify
        env:
        - name: PROCESSES
          value: crawler
