apiVersion: v1
kind: Service
metadata:
  name: identify-api
  labels:
    app: identify
spec:
  type: LoadBalancer
  selector:
    app: identify
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
